### ISSUE TITLE
Any chance of Ultima V?

### ISSUE THREAD

**Issue by tanabi** [ergonomy-joe/u4-decompiled#1]
Hi there! :)

Any chance you'd do a decompile of Ultima V?  If not, can you tell me some of the tools you used, and I'll give it a shot myself...!

Thanks!

**Comment by tanabi** [comment]
Just pinging this on the off chance you'll check it!

**Comment by ergonomy-joe** [comment]
Hi there.
Fisrt sorry for the long delay.
Second, sorry for the bad news: Ultima V has little chances of being reversed by me.
I couldn't reproduce the order of the modules after the linker phase (Phoenix Overlay linker I think) which makes it very hard to compare my code to the original code (that sentence hardly makes sense). 
And that's too bad because I really like Ultima V.

Let's go back to Ultima IV. As for the tools, I used "debug" to disassemble the EXE. Then converted the asm code back to C and rebuild with what I believe is the original compiler: Microsoft C v4.0
And then with error/retrial I could recreate a C version of the program that build almost identically to the original one.
