### ISSUE TITLE
Error trying to run

### ISSUE THREAD

**Issue by Fenyx4** [ergonomy-joe/u4-decompiled#3]
Heya,
I'm trying to compile with the ForVS. I'm on VS 2017. Had to install C extensions and windows SDK to get it to compile.
But when I run it I get this error;

```
low_init
low_gra
dalloc(00004000)
dalloc(00000800)
dopen("CHARSET.CGA", 0)
<err>
```

I've tried putting the orginal files in the same directory and in a sub directory called 'original'. But that didn't work.
What am I doing wrong? Do the original files need to go somewhere else or anywhere at all?

**Comment by cambragol** [comment]
I wish I could help you out, but I haven't tackled the VS build yet. Ergonomy-joe will likely answer, though he only seems to pop in here from time to time.

**Comment by ergonomy-joe** [comment]
Congratulations on building the code Fenyx4.
And sorry for the delay.
I think the problem comes from the macro U4_ROOT in file common.h.
It is the path to the game's file abdos hardcoded to my config.
Bad coding indeed.
If you change the content or the macro toi should be able to run the game.
Tell me if this works for you.

**Comment by Fenyx4** [comment]
Sorry between my original message and your response I had a kid so it has taken my awhile to get back to this. :)

Yes! Updating U4_ROOT did fix the problem. Thank you.
